### ISSUE TITLE
406 Error

### ISSUE THREAD

**Issue by annapritchard** [singer-io/tap-typeform#10]
I have been running a Typeform integration successfully for about a month. Today I received the error:

"406 Client Error: Not Acceptable for url: https://api.typeform.com/forms/my_typeform_identifier"

I tried removing a couple of specific forms, but received the same response.

**Comment by rodrigotassinari** [comment]
I'm having the same error since yesterday at 2019-08-28 12:19:00Z. The integration had been running successfully for several months without any issue. I couldn't find any change on the Typeform API. I've also contacted tham but no response so far.

This is the log of one of the failed extrations:

```
2019-08-28 12:19:00,042Z   main - INFO Running tap-typeform version 1.1.2 and target-stitch version 1.8.1
2019-08-28 12:19:00,126Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-typeform --config /tmp/tap_discover_config.json --discover
2019-08-28 12:19:00,318Z   main - INFO Tap exited normally.
2019-08-28 12:19:00,318Z   main - INFO Saving list of discovered streams
2019-08-28 12:19:00,496Z   main - INFO Saving structure of stream landings
2019-08-28 12:19:00,931Z   main - INFO Saving structure of stream answers
2019-08-28 12:19:01,006Z   main - INFO Saving structure of stream questions
2019-08-28 12:19:01,036Z   main - INFO Getting list of selected properties
2019-08-28 12:19:01,192Z   main - INFO Starting tap: tap-env/bin/tap-typeform --config /tmp/tap_config.json --properties /tmp/properties.json --catalog /tmp/catalog.json --state /tmp/tap_state.json
2019-08-28 12:19:01,194Z   main - INFO Starting target: target-env/bin/target-stitch --config /tmp/target_config.json
2019-08-28 12:19:01,358Z    tap - INFO form: GcBbEa 
2019-08-28 12:19:01,396Z    tap - ERROR 406 - <html>
2019-08-28 12:19:01,397Z    tap - <head><title>406 Not Acceptable</title></head>
2019-08-28 12:19:01,397Z    tap - <body>
2019-08-28 12:19:01,397Z    tap - <center><h1>406 Not Acceptable</h1></center>
2019-08-28 12:19:01,397Z    tap - <hr><center>nginx</center>
2019-08-28 12:19:01,397Z    tap - </body>
2019-08-28 12:19:01,397Z    tap - </html>
2019-08-28 12:19:01,397Z    tap - 
2019-08-28 12:19:01,398Z    tap - INFO "form definition GcBbEa" job took 0.0s, ended with status "failed"
2019-08-28 12:19:01,398Z    tap - CRITICAL 406 Client Error: Not Acceptable for url: https://api.typeform.com/forms/GcBbEa
2019-08-28 12:19:01,399Z    tap - Traceback (most recent call last):
2019-08-28 12:19:01,400Z    tap -   File "tap-env/bin/tap-typeform", line 10, in <module>
2019-08-28 12:19:01,400Z    tap -     sys.exit(main())
2019-08-28 12:19:01,400Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 225, in wrapped
2019-08-28 12:19:01,400Z    tap -     return fnc(*args, **kwargs)
2019-08-28 12:19:01,400Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_typeform/__init__.py", line 95, in main
2019-08-28 12:19:01,400Z    tap -     sync(atx)
2019-08-28 12:19:01,400Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_typeform/__init__.py", line 76, in sync
2019-08-28 12:19:01,400Z    tap -     streams.sync_forms(atx)
2019-08-28 12:19:01,400Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_typeform/streams.py", line 207, in sync_forms
2019-08-28 12:19:01,400Z    tap -     sync_form_definition(atx, form_id)
2019-08-28 12:19:01,400Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_typeform/streams.py", line 98, in sync_form_definition
2019-08-28 12:19:01,400Z    tap -     response = get_form_definition(atx, form_id)
2019-08-28 12:19:01,400Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff.py", line 286, in retry
2019-08-28 12:19:01,400Z    tap -     ret = target(*args, **kwargs)
2019-08-28 12:19:01,400Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff.py", line 286, in retry
2019-08-28 12:19:01,400Z    tap -     ret = target(*args, **kwargs)
2019-08-28 12:19:01,400Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/ratelimit/decorators.py", line 113, in wrapper
2019-08-28 12:19:01,400Z    tap -     return func(*args, **kargs)
2019-08-28 12:19:01,400Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/ratelimit/decorators.py", line 80, in wrapper
2019-08-28 12:19:01,401Z    tap -     return func(*args, **kargs)
2019-08-28 12:19:01,401Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_typeform/streams.py", line 74, in get_form_definition
2019-08-28 12:19:01,401Z    tap -     return atx.client.get(form_id)
2019-08-28 12:19:01,401Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_typeform/http.py", line 57, in get
2019-08-28 12:19:01,401Z    tap -     return self.request('get', form_id, **kwargs)
2019-08-28 12:19:01,401Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff.py", line 286, in retry
2019-08-28 12:19:01,401Z    tap -     ret = target(*args, **kwargs)
2019-08-28 12:19:01,401Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_typeform/http.py", line 48, in request
2019-08-28 12:19:01,401Z    tap -     response.raise_for_status()
2019-08-28 12:19:01,401Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
2019-08-28 12:19:01,401Z    tap -     raise HTTPError(http_error_msg, response=self)
2019-08-28 12:19:01,401Z    tap - requests.exceptions.HTTPError: 406 Client Error: Not Acceptable for url: https://api.typeform.com/forms/GcBbEa
2019-08-28 12:19:01,427Z target - INFO Using Stitch import URL https://api.stitchdata.com/v2/import/batch
2019-08-28 12:19:01,428Z target - INFO Exiting normally
2019-08-28 12:19:01,456Z   main - INFO Target exited normally with status 0
2019-08-28 12:19:01,457Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "406 Client Error: Not Acceptable for url: https://api.typeform.com/forms/GcBbEa". Target succeeded.
```

**Comment by annapritchard** [comment]
This morning the integration ran successfully, but did not load any data. Here is the log of the successful extraction record:


```
2019-08-29 17:35:37,937Z    tap - INFO form: wPiP71 
2019-08-29 17:35:38,101Z    tap - INFO "form definition wPiP71" job took 0.2s, ended with status "succeeded"
2019-08-29 17:35:38,103Z    tap - INFO replicated 14 records from "questions" endpoint
2019-08-29 17:35:38,103Z    tap - INFO start_date: 2019-06-01T00:00:00+00:00 
2019-08-29 17:35:38,103Z    tap - INFO end_date: 2019-08-29T00:00:00+00:00 
2019-08-29 17:35:38,104Z    tap - INFO last_date: 2019-08-27T07:00:00+00:00 
2019-08-29 17:35:38,104Z    tap - INFO ut_current_date: 1566889200 
2019-08-29 17:35:38,104Z    tap - INFO ut_next_date: 1566975600 
2019-08-29 17:35:43,847Z    tap - INFO Forms query - form: wPiP71 start_date: 2019-08-27 07:00 end_date: 2019-08-28 07:00 
2019-08-29 17:35:44,013Z    tap - INFO raw data items= 0
2019-08-29 17:35:44,013Z    tap - INFO "form wPiP71" job took 5.9s, ended with status "succeeded"
2019-08-29 17:35:44,014Z    tap - INFO replicated 0 records from "landings" endpoint
2019-08-29 17:35:44,014Z    tap - INFO replicated 0 records from "answers" endpoint
2019-08-29 17:35:44,015Z    tap - INFO ut_current_date: 1566975600 
2019-08-29 17:35:44,015Z    tap - INFO ut_next_date: 1567062000 
2019-08-29 17:35:49,851Z    tap - INFO Forms query - form: wPiP71 start_date: 2019-08-28 07:00 end_date: 2019-08-29 07:00 
2019-08-29 17:35:49,948Z    tap - INFO raw data items= 0
2019-08-29 17:35:49,948Z    tap - INFO "form wPiP71" job took 5.9s, ended with status "succeeded"
2019-08-29 17:35:49,949Z    tap - INFO replicated 0 records from "landings" endpoint
2019-08-29 17:35:49,951Z    tap - INFO replicated 0 records from "answers" endpoint

```

**Comment by rodrigotassinari** [comment]
It also started working again here since a few minutes agora. No idea why. But it means it's probably something on Typeform's side. I believe this issue can be closed now.
