### ISSUE TITLE
403 error on web forms with correct API token

### ISSUE THREAD

**Issue by TheRealDarb** [singer-io/tap-typeform#38]
Creating an issue to report the same error that others have reported in comments elsewhere. Seemingly coinciding with PR #34, Stitch --> Typeform integrations are failing on the first form it hits. Have tried removing a form and re-running (only to fail on the next form in the list) and regenerating tokens on Typeform.

We don't run Stitch extractions on weekends, so we noticed this as of this morning (7/26)

CC [this comment from austin-e](https://github.com/singer-io/tap-typeform/pull/37#issuecomment-886907165) + 2 other comments (that I can't for the life of me find again....)

**Comment by austin-e** [comment]
FWIW, we were on support with Stitch and they said they were seeing this error and would revert to 1.2.0 (@7/26 2pm ET). 

We now see 1.2.0 in the extraction log, but have the exact same error. I can't say if the reversion actually worked though...

**Comment by sjlogan** [comment]
I am also experiencing this 403 error issue. Stitch recommended that I ask for support here. In lieu of opening an identical issue, I wanted to piggy back on this so it is clear the issue is affecting multiple people.

**Comment by littlesweet1129** [comment]
same issue here `403 Client Error: Forbidden for url: https://api.typeform.com/forms/SmcyTa` with Stitch's Tyepform connector. It has been failing since 07/24/2021.

**Comment by Hera94** [comment]
same issue here 403 Client Error: Forbidden for url: https://api.typeform.com/forms/SmcyTa with Stitch's Typeform connector.

**Comment by jessica-ol** [comment]
Also having the same issue: 403 Client Error: Forbidden for url: https://api.typeform.com/forms/[formID] with Stitch

**Comment by saghatelian** [comment]
Same issue here. Wrote to Stitch support 3 days ago. Still no answer.

**Comment by TomaszE** [comment]
same issue - 403 client error forbidden for url.. tried to  generate new API token with full read/write permissions- that did not help. 

Logs below: ( hashed form id )

2021-07-28 11:21:43,660Z   main - INFO Running tap-typeform version 1.3.2 and target-stitch version 3.2.0
2021-07-28 11:21:44,812Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobStarted ), use_ssl( true )
2021-07-28 11:21:44,815Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobFinished ), use_ssl( true )
2021-07-28 11:21:44,815Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.streamRecordCount ), use_ssl( true )
2021-07-28 11:21:45,820Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobStarted [42] at offset None
2021-07-28 11:21:45,822Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-typeform --config /tmp/tap_discover_config.json --discover
2021-07-28 11:21:45,991Z   main - INFO Tap exited normally.
2021-07-28 11:21:45,991Z   main - INFO Saving list of discovered streams
2021-07-28 11:21:46,012Z   main - INFO Saving structure of stream landings (tap_stream_id: landings)
2021-07-28 11:21:46,024Z   main - INFO Saving structure of stream answers (tap_stream_id: answers)
2021-07-28 11:21:46,041Z   main - INFO Saving structure of stream questions (tap_stream_id: questions)
2021-07-28 11:21:46,052Z   main - INFO Writing catalog to file
2021-07-28 11:21:46,054Z   main - INFO Selected fields for stream answers: ref, landing_id, data_type, type, answer, question_id
2021-07-28 11:21:46,054Z   main - INFO Selected fields for stream landings: platform, network_id, landed_at, submitted_at, referer, user_agent, token, hidden, browser, landing_id
2021-07-28 11:21:46,054Z   main - INFO Selected fields for stream questions: title, form_id, question_id, ref
2021-07-28 11:21:46,058Z   main - INFO Current state: {"bookmarks": {"#########": {"date_to_resume": "2021-07-24 00:00:00"}, "######": {"date_to_resume": "2021-06-28 12:42:42"}}}
2021-07-28 11:21:46,058Z   main - INFO Starting tap: tap-env/bin/tap-typeform --config /tmp/tap_config.json --properties /tmp/properties.json --catalog /tmp/catalog.json --state /tmp/tap_state.json
2021-07-28 11:21:46,061Z   main - INFO Starting target: target-env/bin/target-stitch --config /tmp/target_config.json
2021-07-28 11:21:46,186Z    tap - INFO form: ###### 
2021-07-28 11:21:46,264Z    tap - ERROR 403 - <html>
2021-07-28 11:21:46,265Z    tap - <head><title>403 Forbidden</title></head>
2021-07-28 11:21:46,265Z    tap - <body>
2021-07-28 11:21:46,265Z    tap - <center><h1>403 Forbidden</h1></center>
2021-07-28 11:21:46,265Z    tap - </body>
2021-07-28 11:21:46,265Z    tap - </html>
2021-07-28 11:21:46,265Z    tap - 
2021-07-28 11:21:46,349Z    tap - INFO "form definition BXQ5xNs3" job took 0.1s, ended with status "failed"
2021-07-28 11:21:46,350Z    tap - CRITICAL 403 Client Error: Forbidden for url: https://api.typeform.com/forms/BXQ5xNs3
2021-07-28 11:21:46,350Z    tap - Traceback (most recent call last):
2021-07-28 11:21:46,350Z    tap -   File "tap-env/bin/tap-typeform", line 33, in <module>
2021-07-28 11:21:46,350Z    tap -     sys.exit(load_entry_point('tap-typeform==1.3.2', 'console_scripts', 'tap-typeform')())
2021-07-28 11:21:46,350Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/singer/utils.py", line 225, in wrapped
2021-07-28 11:21:46,350Z    tap -     return fnc(*args, **kwargs)
2021-07-28 11:21:46,350Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/tap_typeform/__init__.py", line 95, in main
2021-07-28 11:21:46,350Z    tap -     sync(atx)
2021-07-28 11:21:46,350Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/tap_typeform/__init__.py", line 76, in sync
2021-07-28 11:21:46,350Z    tap -     streams.sync_forms(atx)
2021-07-28 11:21:46,350Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/tap_typeform/streams.py", line 207, in sync_forms
2021-07-28 11:21:46,350Z    tap -     sync_form_definition(atx, form_id)
2021-07-28 11:21:46,350Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/tap_typeform/streams.py", line 98, in sync_form_definition
2021-07-28 11:21:46,350Z    tap -     response = get_form_definition(atx, form_id)
2021-07-28 11:21:46,350Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/backoff.py", line 286, in retry
2021-07-28 11:21:46,350Z    tap -     ret = target(*args, **kwargs)
2021-07-28 11:21:46,350Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/backoff.py", line 286, in retry
2021-07-28 11:21:46,350Z    tap -     ret = target(*args, **kwargs)
2021-07-28 11:21:46,350Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/ratelimit/decorators.py", line 113, in wrapper
2021-07-28 11:21:46,350Z    tap -     return func(*args, **kargs)
2021-07-28 11:21:46,351Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/ratelimit/decorators.py", line 80, in wrapper
2021-07-28 11:21:46,351Z    tap -     return func(*args, **kargs)
2021-07-28 11:21:46,351Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/tap_typeform/streams.py", line 74, in get_form_definition
2021-07-28 11:21:46,351Z    tap -     return atx.client.get(form_id)
2021-07-28 11:21:46,351Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/tap_typeform/http.py", line 57, in get
2021-07-28 11:21:46,351Z    tap -     return self.request('get', form_id, **kwargs)
2021-07-28 11:21:46,351Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/backoff.py", line 286, in retry
2021-07-28 11:21:46,351Z    tap -     ret = target(*args, **kwargs)
2021-07-28 11:21:46,351Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/tap_typeform/http.py", line 48, in request
2021-07-28 11:21:46,351Z    tap -     response.raise_for_status()
2021-07-28 11:21:46,351Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
2021-07-28 11:21:46,351Z    tap -     raise HTTPError(http_error_msg, response=self)
2021-07-28 11:21:46,351Z    tap - requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.typeform.com/forms/#########
2021-07-28 11:21:46,463Z target - INFO Using batch_size_prefernces of {'batch_size_preference': None, 'user_batch_size_preference': None, 'full_table_streams': []}
2021-07-28 11:21:46,463Z target - INFO Requests complete, stopping loop
2021-07-28 11:21:46,506Z   main - INFO Target exited normally with status 0
2021-07-28 11:21:47,359Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobFinished [22] at offset None
2021-07-28 11:21:47,364Z   main - INFO No tunnel subprocess to tear down
2021-07-28 11:21:47,365Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "403 Client Error: Forbidden for url: https://api.typeform.com/forms/#########". Target succeeded.

**Comment by yinafoodles** [comment]
Same issue as well, we have been failling from 23/07/2021 at 22h30 GMT +1 . Support Stitch has no solution :(

**Comment by omulvenna** [comment]
Likewise we have been experiencing this issue since 23/07. We first got errors at 16h00. Is there any update on a fix?

**Comment by littlesweet1129** [comment]
same question as above^^

**Comment by jonathanasquier** [comment]
Commenting for updates :pray:

**Comment by luandy64** [comment]
Hi everyone,

We discovered late Friday 7/30 requests coming from within the Stitch infrastructure are hitting this 403. 

I'm in contact with Typeform Support to give them the information they need to investigate this issue on their side. 

---

All of your tokens should be working still. You can test them against queries the tap is making. Using `curl` the `GET`s would look like

``` sh
curl -H 'Authorization: Bearer mytoken123' https://api.typeform.com/forms
curl -H 'Authorization: Bearer mytoken123' https://api.typeform.com/forms/t6sbkCIz
curl -H 'Authorization: Bearer mytoken123' https://api.typeform.com/forms/t6sbkCIz/responses
```
Replace `mytoken123` with your actual token; replace `t6sbkClz` with your form ID.

Or use Postman/Insomnia or your favorite REST client to make the same requests

---

I still believe release `v1.3.0` is fine and will push for #42 to go out. I will try to update this thread when I know more. 

If you have other questions, please reach out in the `#tap-typeform` channel in the Singer Slack

**Comment by luandy64** [comment]
This should be resolved

**Comment by murillo-ro-silva** [comment]
Hi @luandy64!

How's it going? 

Recently, I took errors of authentication in a row week after week. I just need to re-authorize and everything going back resolved. Is it errors look like with that? Is anyone took some errors such that?
![image](https://github.com/singer-io/tap-typeform/assets/719341/e08d6517-19c7-4dd9-bcb2-7262be50f1a7)
