### ISSUE TITLE
KeyError in answers stream

### ISSUE THREAD

**Issue by amyfain** [singer-io/tap-typeform#4]
We are hitting a KeyError in the answers stream:

```2019-02-05 21:36:22,589Z    tap - CRITICAL 'fileupload'
2019-02-05 21:36:22,589Z    tap - Traceback (most recent call last):
2019-02-05 21:36:22,589Z    tap -   File "tap-env/bin/tap-typeform", line 10, in <module>
2019-02-05 21:36:22,590Z    tap -     sys.exit(main())
2019-02-05 21:36:22,590Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 225, in wrapped
2019-02-05 21:36:22,590Z    tap -     return fnc(*args, **kwargs)
2019-02-05 21:36:22,590Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_typeform/__init__.py", line 95, in main
2019-02-05 21:36:22,590Z    tap -     sync(atx)
2019-02-05 21:36:22,590Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_typeform/__init__.py", line 76, in sync
2019-02-05 21:36:22,590Z    tap -     streams.sync_forms(atx)
2019-02-05 21:36:22,590Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_typeform/streams.py", line 261, in sync_forms
2019-02-05 21:36:22,590Z    tap -     [responses, max_submitted_at] = sync_form(atx, form_id, ut_current_date, ut_next_date)
2019-02-05 21:36:22,590Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_typeform/streams.py", line 174, in sync_form
2019-02-05 21:36:22,590Z    tap -     answer_value = answer[data_type]
2019-02-05 21:36:22,591Z    tap - KeyError: 'fileupload'```

**Comment by luandy64** [comment]
I'm closing this issue, but if it's still a problem, feel free to reopen this or open a new issue 👍
