### ISSUE TITLE
Error with desciption "'fields'"

### ISSUE THREAD

**Issue by TomaszE** [singer-io/tap-typeform#8]
Hi guys,

we have a problem with our integration - we have few different typeforms we are integrating, we don't have problems with most , but in one we are getting error that does not say anything to me ...

`
Today at 1:00 am

Error
Encountered an error while attempting to replicate data from . The message was:

'fields'

`

Below in comment full log. 

Thanks

**Comment by TomaszE** [comment]
2019-03-20 00:00:31,260Z   main - INFO Running tap-typeform version 1.1.2 and target-stitch version 1.8.1
2019-03-20 00:00:31,338Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-typeform --config /tmp/tap_discover_config.json --discover
2019-03-20 00:00:31,553Z   main - INFO Tap exited normally.
2019-03-20 00:00:31,553Z   main - INFO Saving list of discovered streams
2019-03-20 00:00:31,607Z   main - INFO Saving structure of stream landings
2019-03-20 00:00:31,644Z   main - INFO Saving structure of stream answers
2019-03-20 00:00:31,736Z   main - INFO Saving structure of stream questions
2019-03-20 00:00:31,801Z   main - INFO Getting list of selected properties
2019-03-20 00:00:31,859Z   main - INFO Starting tap: tap-env/bin/tap-typeform --config /tmp/tap_config.json --properties /tmp/properties.json --catalog /tmp/catalog.json --state /tmp/tap_state.json
2019-03-20 00:00:31,862Z   main - INFO Starting target: target-env/bin/target-stitch --config /tmp/target_config.json
2019-03-20 00:00:32,044Z    tap - INFO form: RQQ4Bz 
2019-03-20 00:00:32,118Z target - INFO Using Stitch import URL https://api.stitchdata.com/v2/import/batch
2019-03-20 00:00:32,182Z    tap - INFO "form definition RQQ4Bz" job took 0.1s, ended with status "failed"
2019-03-20 00:00:32,182Z    tap - CRITICAL 'fields'
2019-03-20 00:00:32,182Z    tap - Traceback (most recent call last):
2019-03-20 00:00:32,182Z    tap -   File "tap-env/bin/tap-typeform", line 10, in <module>
2019-03-20 00:00:32,183Z    tap -     sys.exit(main())
2019-03-20 00:00:32,183Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 225, in wrapped
2019-03-20 00:00:32,183Z    tap -     return fnc(*args, **kwargs)
2019-03-20 00:00:32,183Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_typeform/__init__.py", line 95, in main
2019-03-20 00:00:32,183Z    tap -     sync(atx)
2019-03-20 00:00:32,183Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_typeform/__init__.py", line 76, in sync
2019-03-20 00:00:32,183Z    tap -     streams.sync_forms(atx)
2019-03-20 00:00:32,183Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_typeform/streams.py", line 207, in sync_forms
2019-03-20 00:00:32,183Z    tap -     sync_form_definition(atx, form_id)
2019-03-20 00:00:32,183Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_typeform/streams.py", line 99, in sync_form_definition
2019-03-20 00:00:32,183Z    tap -     data = response['fields']
2019-03-20 00:00:32,183Z    tap - KeyError: 'fields'
2019-03-20 00:00:32,206Z target - INFO Exiting normally
2019-03-20 00:00:32,254Z   main - INFO Target exited normally with status 0
2019-03-20 00:00:32,255Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "'fields'". Target succeeded.

**Comment by TomaszE** [comment]
Hi , I know there is not much data here - but can someone look at the issue ?
